/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-error': '#690005',
        'on-tertiary-fixed-variant': '#004e5d',
        'on-background': '#e5e2e1',
        'tertiary': '#72d4ef',
        'on-primary-fixed-variant': '#93000d',
        'primary-fixed-dim': '#ffb4ac',
        'on-primary-container': '#5c0005',
        'surface-container': '#202020',
        'outline': '#ab8985',
        'surface-container-highest': '#353535',
        'surface': '#131313',
        'secondary-fixed': '#ffdad6',
        'primary-fixed': '#ffdad6',
        'on-secondary-fixed-variant': '#93000b',
        'on-primary-fixed': '#410002',
        'on-secondary-container': '#ffa99f',
        'on-primary': '#690006',
        'on-surface': '#e5e2e1',
        'background': '#131313',
        'on-tertiary': '#003641',
        'tertiary-fixed': '#afecff',
        'inverse-on-surface': '#303030',
        'surface-container-high': '#2a2a2a',
        'primary': '#ffb4ac',
        'inverse-surface': '#e5e2e1',
        'surface-container-low': '#1b1b1c',
        'secondary-container': '#a0030e',
        'on-secondary': '#690005',
        'on-surface-variant': '#e4beb9',
        'on-tertiary-container': '#002e39',
        'tertiary-fixed-dim': '#72d4ef',
        'inverse-primary': '#bb171c',
        'secondary-fixed-dim': '#ffb4ab',
        'on-tertiary-fixed': '#001f27',
        'surface-variant': '#353535',
        'surface-tint': '#ffb4ac',
        'error': '#ffb4ab',
        'surface-dim': '#131313',
        'primary-container': '#ff544c',
        'outline-variant': '#5b403d',
        'error-container': '#93000a',
        'secondary': '#ffb4ab',
        'surface-container-lowest': '#0e0e0e',
        'surface-bright': '#393939',
        'on-error-container': '#ffdad6',
        'tertiary-container': '#319db6',
        'on-secondary-fixed': '#410002'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px'
      },
      spacing: {
        'space-xxs': '0.25rem',
        'space-md': '1.5rem',
        'space-lg': '2rem',
        'space-xl': '2.5rem',
        'space-xs': '0.5rem',
        'space-xxl': '3rem',
        'space-sm': '1rem'
      },
      fontFamily: {
        'body-md': ['Plus Jakarta Sans'],
        'display-mobile': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'display': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans']
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '400' }],
        'display-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-sm': ['16px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '30px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-sm': ['10px', { lineHeight: '12px', letterSpacing: '0.04em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }]
      }
    },
  },
  plugins: [],
}
